name: CBOE options rolling parquet

on:
  workflow_run:
    workflows: ["CBOE options daily parquet"]
    branches: [main]
    types: 
      - completed
  workflow_dispatch: # Allow manual trigger from GitHub Actions UI
    inputs:
      rolling_days:
        description: 'Number of rolling days'
        required: false
        default: '30'

permissions:
  contents: write

jobs:
  set-release-vars:    
    runs-on: ubuntu-latest
    if: ${{ github.event.workflow_run.conclusion == 'success' || github.event_name == 'workflow_dispatch' }}
    outputs:
      cboerolling-tag: ${{ steps.cboerollingdata.outputs.RELEASE_NAME }}      
    steps:
      - id: cboerollingdata
        run: echo "RELEASE_NAME=CBOE_ROLLING_$(date '+%Y-%m-%d-%H-%M-%S')" >> ${GITHUB_OUTPUT}

  cboe-options-rolling-parquet:
    runs-on: ubuntu-latest
    needs: set-release-vars
    env:
      RELEASE_NAME: ${{needs.set-release-vars.outputs.cboerolling-tag}}
      ROLLING_DAYS: ${{ github.event.inputs.rolling_days }}
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: "3.9" # Specify your Python version
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install pandas requests pyarrow duckdb
      - name: Run the Python script
        run: python jobs/main-options-cboe-consolidate.py
      - name: Upload artifacts 
        uses: actions/upload-artifact@v4
        with:
          name: cboe-rolling-data
          if-no-files-found: error
          path: |
            ${{ github.workspace}}/temp/*.parquet
            ${{ github.workspace}}/temp/*.csv
            ${{ github.workspace}}/data/cboe-options-rolling.json            
  release-cboe-rolling-data:
    runs-on: ubuntu-latest
    needs: [set-release-vars, cboe-options-rolling-parquet]
    env:
      RELEASE_NAME: ${{needs.set-release-vars.outputs.cboerolling-tag}}
    steps:
      - name: Setup repo
        uses: actions/checkout@v4
        with:
          fetch-depth: 0   # Fetch all commits to ensure the latest state is available
          ref: main        # Ensure the latest state from the main branch is checked out
      - name: Download snapshot images Artifact
        uses: actions/download-artifact@v4
        with:
          name: cboe-rolling-data
      - name: Release
        uses: mnsrulz/action-gh-release@master
        with:
          files: "temp/*.*"
          tag_name: ${{ env.RELEASE_NAME }}
      - name: Commit and push changes
        run: |
          git config --global user.name "GitHub Actions"
          git config --global user.email "actions@github.com"
          git add --all
          if git diff-index --quiet HEAD; then
            echo "No changes to commit."
          else
            git commit -m "Update data/cboe-options-consolidated.json (via GitHub Actions)"
            git push
          fi
