name: Deploy to mztradingsnapshotcdn
on:
  push:
    branches: main
  workflow_run:
    workflows: ["Publish snapshots"]
    branches: [main]
    types: 
      - completed
  workflow_dispatch: # Allow manual trigger from GitHub Actions UI

jobs:
  deploy:
    name: Deploy
    runs-on: ubuntu-latest

    # permissions:
    #   id-token: write # Needed for auth with Deno Deploy
    #   contents: read # Needed to clone the repository

    steps:
      - name: Clone repository
        uses: actions/checkout@v4

      - name: Upload to Deno Deploy
        env:
          DENO_DEPLOY_TOKEN: ${{ secrets.DENO_DEPLOY_TOKEN }}
        uses: denoland/deployctl@v1
        with:
          project: "mztradingsnapshotcdn"
          entrypoint: "api/snapshot-cdn.ts"
